# Generated by Django 4.1.6 on 2023-03-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_rename_sur_name_author_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='М', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='actors',
            field=models.ManyToManyField(to='book_app.character'),
        ),
    ]
